baseURL = "singhch.in"
languageCode = "en-us"
title = "singh"
theme="archie"
favicon="ğŸ­"
copyright = "Â© csingh"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3

# [[menu.main]]
# name = "notes"
# url = "https://singhch.in/notes"
# weight = 4


[[menu.main]]
name = "about"
url = "/about"
weight = 4
